In [11]:
import numpy as np

In [12]:
arr1 = np.array([1,3,2,7,2,6,9,70,10,20,49,6,324,35])
print(arr1)

[  1   3   2   7   2   6   9  70  10  20  49   6 324  35]


In [13]:
# 1.1 Boolean condition - doesn't directly give you the values. It creates a Boolean mask.
print(arr1 > 9) 

[False False False False False False False  True  True  True  True False
  True  True]


In [16]:
print(arr1 == 70)
print(arr1 != 49)
print(arr1 > 40)
print(arr1 < 60)
print(arr1 <= 30)
print(arr1 >= 35)

[False False False False False False False  True False False False False
 False False]
[ True  True  True  True  True  True  True  True  True  True False  True
  True  True]
[False False False False False False False  True False False  True False
  True False]
[ True  True  True  True  True  True  True False  True  True  True  True
 False  True]
[ True  True  True  True  True  True  True False  True  True False  True
 False False]
[False False False False False False False  True False False  True False
  True  True]


In [18]:
# 1.2 True / False Mask - A mask is simply an array of True and False.
print(arr1 > 40)

[False False False False False False False  True False False  True False
  True False]


In [19]:
print(arr1[arr1 > 60])

[ 70 324]


In [24]:
# 1.3 Filtering Values- This is essentially filtering rows based on a condition, which you'll use heavily later in Pandas.
sales = np.array([1200,356,2000,480,4500,3421,857])
print(sales)

[1200  356 2000  480 4500 3421  857]


In [25]:
print(sales[sales > 2000])

[4500 3421]


In [27]:
print(sales[sales < 1000])

[356 480 857]


In [29]:
print(sales[sales == 480])

[480]


In [32]:
# 1.4 Multiple Conditions - They are important when combining conditions.
arr3 = np.array([100,0,2341,3412,647,2421,9080])
print(arr3)

[ 100    0 2341 3412  647 2421 9080]


In [33]:
print(arr3[(arr3 >= 2000) & (arr3 <= 5000)])

[2341 3412 2421]


In [34]:
#1.5, AND - & means both conditions must be True.
arr4 = np.array([1000,2346,8643,5735,1231,4326])
print(arr4)

[1000 2346 8643 5735 1231 4326]


In [35]:
print(arr3[(arr3 > 2000) & (arr3 < 6000)])

[2341 3412 2421]


In [43]:
# 1.6, — OR- | means at least one condition must be True.
arr5 = np.array([91208,4325,352,8528,5646,1231,3242,5467])
print(arr5)

[91208  4325   352  8528  5646  1231  3242  5467]


In [44]:
print(arr5[(arr5 > 3000) | (arr5 < 1000 )])

[91208  4325   352  8528  5646  3242  5467]


In [48]:
# 1.7, — NOT- ~ reverses a Boolean condition.
arr6 = np.array([123,3242,4535,3473,1285,9267,3528])
print(arr6)

[ 123 3242 4535 3473 1285 9267 3528]


In [49]:
print(arr6[arr6 > 3000])


[3242 4535 3473 9267 3528]


In [50]:
print(arr6[~(arr6 > 3000)])

[ 123 1285]


In [51]:
# 2. Fancy Indexing - Fancy indexing means selecting elements using an array/list of indices.

In [52]:
# 2.1 Selecting Specific Positions
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [53]:
print(arr[[0,1,4]])  # selects multiple positions.

[10 20 50]


In [58]:
print(arr[2])  # selects one position.

30


In [59]:
#2.2 Selecting Multiple Rows - For a 2D array: - So fancy indexing isn't restricted to sequential positions.
data = np.array([
    [101, 500],
    [102, 700],
    [103, 900],
    [104, 1200]
])
print(data[[0,3]])

[[ 101  500]
 [ 104 1200]]


In [60]:
print(data[[3,1,0]]) # You can also select rows in any order:

[[ 104 1200]
 [ 102  700]
 [ 101  500]]


In [62]:
# 2.3 Selecting Multiple Columns
data = np.array([
    [101, 500, 10],
    [102, 700, 20],
    [103, 900, 30]
])
print(data)

[[101 500  10]
 [102 700  20]
 [103 900  30]]


In [63]:
print(data[ : ,[0,2]])

[[101  10]
 [102  20]
 [103  30]]


In [64]:
# 2.4 Combining Row & Column Selection
data = np.array([
    [101,5000,10],
    [102,700,95],
    [103,458,548],
    [104,215,672]])
print(data)

[[ 101 5000   10]
 [ 102  700   95]
 [ 103  458  548]
 [ 104  215  672]]


In [71]:
data[np.ix_([0, 2], [1, 2])] # - It creates the proper row/column combination for selecting a rectangular subset.
# np.ix_(row_indices, column_indices)

array([[5000,   10],
       [ 458,  548]])

In [73]:
# 3. Boolean + Fancy Indexing
data = np.array([[10,748,258],[102,420,103],[45,302,857],[100,20,85],[40,58,41],[18,52,790]])
print(data)

[[ 10 748 258]
 [102 420 103]
 [ 45 302 857]
 [100  20  85]
 [ 40  58  41]
 [ 18  52 790]]


In [79]:
#  syntax - data[condition, column]
# Find rows where sales > 1000
data[:,1] > 150 #boolean / mask and 1 is column

array([ True,  True,  True, False, False, False])

In [81]:
data[data[:,1] > 150] # - 1 is colmnn 1

array([[ 10, 748, 258],
       [102, 420, 103],
       [ 45, 302, 857]])

In [82]:
data[data[:,1] > 150, 1] # first 1 is column 1 giving input and sec 1 is returning column 1.

array([748, 420, 302])

In [92]:
# Multiple conditions on rows
data[(data[:,1] >=200) & (data[:,2] <= 200)]

array([[102, 420, 103]])

In [97]:
#, Practical Data Analyst Example
sales = np.array([
    [101, 1200, 5],
    [102, 800,  3],
    [103, 2500, 8],
    [104, 1500, 6],
    [105, 500,  2]
])
print(sales)

[[ 101 1200    5]
 [ 102  800    3]
 [ 103 2500    8]
 [ 104 1500    6]
 [ 105  500    2]]


In [100]:
# Products with sales > 1000
print(sales[sales[:,1] > 1000]) # 1 is sales column

[[ 101 1200    5]
 [ 103 2500    8]
 [ 104 1500    6]]


In [102]:
# - Product IDs with sales > 1000
print(sales[sales[:,1]>1000,0])

[101 103 104]


In [105]:
# - Products with sales > 1000 AND quantity > 5
print(sales[(sales[:,1] > 1000) & (sales[:,2] > 5)])

[[ 103 2500    8]
 [ 104 1500    6]]


In [107]:
# Product IDs satisfying both conditions
print(sales[(sales[:,1] > 1000) & (sales[:,2] > 5), 0]) # 0 is 1st column

[103 104]
